begin;
create extension if not exists pgtap with schema extensions;
select plan(16);
select has_table('private','accounts','accounts exist privately');
select has_table('private','games','drafts exist privately');
select has_table('private','publications','public snapshots are separate');
select ok(not has_schema_privilege('anon','private','usage'),'anonymous has no private schema');
select ok(not has_table_privilege('anon','private.games','select'),'anonymous cannot select drafts');
select ok(not has_table_privilege('authenticated','private.games','select'),'owner uses checked RPC, no table SELECT');
select ok(not has_table_privilege('authenticated','private.games','insert'),'no direct INSERT');
select ok(not has_table_privilege('authenticated','private.games','update'),'no direct UPDATE');
select ok(not has_table_privilege('authenticated','private.games','delete'),'no direct DELETE');
select ok(not has_table_privilege('authenticated','private.accounts','update'),'cannot change own plan');
select ok(not has_function_privilege('anon','public.mutate_game(text,jsonb)','execute'),'anonymous cannot mutate');
select ok(has_function_privilege('authenticated','public.mutate_game(text,jsonb)','execute'),'authenticated can call checked mutation');
select ok(not has_function_privilege('authenticated','private.purge_expired_cloud_records()','execute'),'purge is privileged');
select ok((select bool_and(relrowsecurity) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='private' and c.relkind='r'),'private tables also use RLS');
select ok((select bool_and(proconfig @> array['search_path=']) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('creator_context','list_games','load_game','mutate_game')),'fixed empty search_path on public RPCs');
set local role authenticated;
select is(public.creator_context()->'error'->>'code','UNAUTHENTICATED','missing identity fails closed');
reset role;
select * from finish();
rollback;
