begin;
\ir helpers/setup.inc
create temp table test_game as select public.mutate_game('save',pg_temp.args())->'data' as meta;
select is((select meta->>'version' from test_game),'1','first save version 1');
select is(public.creator_context()->'data'->>'plan','free','account provisioned free');
select is(public.load_game((select (meta->>'id')::uuid from test_game))->>'ok','true','owner can load own draft');
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000002',true);
select is(public.load_game((select (meta->>'id')::uuid from test_game))->'error'->>'code','UNAVAILABLE','other owner cannot load draft');
select is(jsonb_array_length(public.list_games()->'data'),0,'other owner cannot list draft');
select is(public.mutate_game('delete',pg_temp.command((select (meta->>'id')::uuid from test_game),1))->'error'->>'code','UNAVAILABLE','other owner cannot delete draft');
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
select is(public.mutate_game('save',pg_temp.args((select (meta->>'id')::uuid from test_game),0))->'error'->>'code','CONFLICT','stale update rejected');
update test_game set meta=public.mutate_game('publish',pg_temp.command((meta->>'id')::uuid,1))->'data';
select is((select meta->'publication'->>'status' from test_game),'published','publication created');
select matches((select meta->'publication'->>'shareId' from test_game),'^[A-Za-z0-9_-]{22}$','opaque 128-bit share ID');
select is((select meta->>'version' from test_game),'2','publish increments game version');
select is((select meta->>'publicationDirty' from test_game),'false','publish leaves content clean');
create temp table original_publication as select meta->'publication' p from test_game;
update test_game set meta=public.mutate_game('save',pg_temp.args((meta->>'id')::uuid,2,pg_temp.project()||'{"title":"変更"}'))->'data';
select is((select meta->>'publicationDirty' from test_game),'true','saving draft does not update snapshot');
select is((select snapshot->>'title' from private.publications where game_id=(select (meta->>'id')::uuid from test_game)),'教材','public snapshot remains original');
update test_game set meta=public.mutate_game('unpublish',pg_temp.command((meta->>'id')::uuid,3))->'data';
select is((select meta->'publication'->>'status' from test_game),'stopped','stop publication');
update test_game set meta=public.mutate_game('republish',pg_temp.command((meta->>'id')::uuid,4))->'data';
select is((select meta->'publication'->>'shareId' from test_game),(select p->>'shareId' from original_publication),'restart retains URL');
select is((select meta->'publication'->>'version' from test_game),'1','restart preserves public snapshot version');
update test_game set meta=public.mutate_game('publish',pg_temp.command((meta->>'id')::uuid,5))->'data';
select is((select meta->'publication'->>'version' from test_game),'2','explicit update increments snapshot version');
select is((select meta->>'publicationDirty' from test_game),'false','explicit update clears dirty');
select is(public.mutate_game('delete',pg_temp.command((select (meta->>'id')::uuid from test_game),6))->'data'->>'deleted','true','owner deletes game');
select is(public.load_game((select (meta->>'id')::uuid from test_game))->'error'->>'code','UNAVAILABLE','deleted game unavailable');
select is((select count(*)::int from private.publications),0,'publication removed with game');
select * from finish();
rollback;
