// Generated by tools/build-shared-function.mjs. Do not edit or add secrets.
(() => {
  // core/cloud/contracts.js
  var ERROR_MESSAGES = Object.freeze({
    NOT_CONFIGURED: "\u30AA\u30F3\u30E9\u30A4\u30F3\u6A5F\u80FD\u306F\u6E96\u5099\u4E2D\u3067\u3059\u3002\u7AEF\u672B\u3078\u306E\u4FDD\u5B58\u306F\u5229\u7528\u3067\u304D\u307E\u3059\u3002",
    UNAUTHENTICATED: "\u4F5C\u6210\u8005\u306E\u30ED\u30B0\u30A4\u30F3\u304C\u5FC5\u8981\u3067\u3059\u3002",
    FORBIDDEN: "\u3053\u306E\u64CD\u4F5C\u306F\u8A31\u53EF\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002",
    UNAVAILABLE: "\u3053\u306E\u30B2\u30FC\u30E0\u306F\u73FE\u5728\u516C\u958B\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002",
    VALIDATION: "\u554F\u984C\u30C7\u30FC\u30BF\u306E\u5F62\u5F0F\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
    LIMIT: "\u7121\u6599\u8A66\u9A13\u904B\u7528\u306E\u4E0A\u9650\u3092\u8D85\u3048\u3066\u3044\u307E\u3059\u3002",
    RATE_LIMIT: "\u64CD\u4F5C\u304C\u96C6\u4E2D\u3057\u3066\u3044\u307E\u3059\u3002\u5C11\u3057\u5F85\u3063\u3066\u304B\u3089\u304A\u8A66\u3057\u304F\u3060\u3055\u3044\u3002",
    CONFLICT: "\u5225\u306E\u5834\u6240\u3067\u66F4\u65B0\u3055\u308C\u3066\u3044\u307E\u3059\u3002\u4E0A\u66F8\u304D\u305B\u305A\u5185\u5BB9\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
    REQUEST_MISMATCH: "\u518D\u8A66\u884C\u3059\u308B\u64CD\u4F5C\u306E\u5185\u5BB9\u304C\u5909\u308F\u308A\u307E\u3057\u305F\u3002",
    NETWORK: "\u901A\u4FE1\u3092\u78BA\u8A8D\u3057\u3001\u3082\u3046\u4E00\u5EA6\u304A\u8A66\u3057\u304F\u3060\u3055\u3044\u3002\u7DE8\u96C6\u4E2D\u306E\u5185\u5BB9\u306F\u305D\u306E\u307E\u307E\u3067\u3059\u3002",
    SERVICE_UNAVAILABLE: "\u30AA\u30F3\u30E9\u30A4\u30F3\u6A5F\u80FD\u3092\u5229\u7528\u3067\u304D\u307E\u305B\u3093\u3002\u3057\u3070\u3089\u304F\u3057\u3066\u304B\u3089\u304A\u8A66\u3057\u304F\u3060\u3055\u3044\u3002"
  });
  var ok = (data) => ({ ok: true, data });
  function failure(code, message = ERROR_MESSAGES[code], retryAfterSeconds) {
    return { ok: false, error: { code, message, ...retryAfterSeconds === void 0 ? {} : { retryAfterSeconds } } };
  }

  // core/cloud/project-validation.js
  var CLOUD_LIMITS = Object.freeze({
    questions: 200,
    bytes: 262144,
    title: 80,
    prompt: 1e3,
    displayAnswer: 200,
    reading: 200,
    romajiHint: 800,
    id: 128
  });
  var record = (v) => v !== null && typeof v === "object" && !Array.isArray(v);
  var keysMatch = (v, keys) => record(v) && Object.keys(v).length === keys.length && keys.every((k) => Object.hasOwn(v, k));
  var validText = (v) => typeof v === "string" && !v.includes("\0") && v.isWellFormed();
  function serializeCloudProject(p) {
    return JSON.stringify({
      schemaVersion: p.schemaVersion,
      title: p.title,
      gameType: p.gameType,
      templateId: p.templateId,
      settings: { volume: p.settings.volume, muted: p.settings.muted },
      questions: p.questions.map((q) => ({ id: q.id, prompt: q.prompt, displayAnswer: q.displayAnswer, reading: q.reading, romajiHint: q.romajiHint }))
    });
  }
  function validateCloudProject(p, { mode = "draft" } = {}) {
    if (!["draft", "publish"].includes(mode) || !keysMatch(p, ["schemaVersion", "title", "gameType", "templateId", "settings", "questions"]) || p.schemaVersion !== 1 || p.gameType !== "typing" || p.templateId !== "fusuma" || !validText(p.title) || !Array.isArray(p.questions) || !keysMatch(p.settings, ["volume", "muted"]) || !Number.isFinite(p.settings.volume) || p.settings.volume < 0 || p.settings.volume > 1 || typeof p.settings.muted !== "boolean") return failure("VALIDATION");
    if ([...p.title].length > CLOUD_LIMITS.title || p.questions.length > CLOUD_LIMITS.questions) return failure("LIMIT");
    if (mode === "publish" && (!p.title.trim() || p.questions.length === 0)) return failure("VALIDATION", "\u516C\u958B\u306B\u306F\u30BB\u30C3\u30C8\u540D\u30681\u554F\u4EE5\u4E0A\u306E\u554F\u984C\u304C\u5FC5\u8981\u3067\u3059\u3002");
    const ids = /* @__PURE__ */ new Set();
    for (const [index, q] of p.questions.entries()) {
      if (!keysMatch(q, ["id", "prompt", "displayAnswer", "reading", "romajiHint"]) || Object.values(q).some((v) => !validText(v)) || !/^[A-Za-z0-9_-]{1,128}$/.test(q.id) || ids.has(q.id)) return failure("VALIDATION", index + 1 + "\u554F\u76EE\u306E\u5F62\u5F0F\u307E\u305F\u306FID\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
      ids.add(q.id);
      for (const key of ["prompt", "displayAnswer", "reading", "romajiHint"]) {
        if ([...q[key]].length > CLOUD_LIMITS[key]) return failure("LIMIT", index + 1 + "\u554F\u76EE\u306E\u6587\u5B57\u6570\u304C\u4E0A\u9650\u3092\u8D85\u3048\u3066\u3044\u307E\u3059\u3002");
        if (mode === "publish" && key !== "romajiHint" && !q[key].trim()) return failure("VALIDATION", index + 1 + "\u554F\u76EE\u306E\u554F\u984C\u30FB\u6B63\u89E3\u30FB\u3088\u307F\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
      }
    }
    const serialized = serializeCloudProject(p);
    if (new TextEncoder().encode(serialized).byteLength > CLOUD_LIMITS.bytes) return failure("LIMIT", "\u30AA\u30F3\u30E9\u30A4\u30F3\u4FDD\u5B58\u306F1\u4EF6256 KiB\u4EE5\u4E0B\u3067\u3059\u3002\u7AEF\u672B\u3078\u306E\u4FDD\u5B58\u306F\u5F15\u304D\u7D9A\u304D\u5229\u7528\u3067\u304D\u307E\u3059\u3002");
    return ok(JSON.parse(serialized));
  }

  // core/cloud/share-url.js
  var SHARE_ID_PATTERN = /^[A-Za-z0-9_-]{22}$/;
  function parseShareId(input) {
    try {
      const url = new URL(input);
      const entries = [...url.searchParams.entries()];
      if (!["https:", "http:"].includes(url.protocol) || url.hash || url.username || url.password || entries.length !== 1 || entries[0][0] !== "g" || !SHARE_ID_PATTERN.test(entries[0][1])) return null;
      return entries[0][1];
    } catch {
      return null;
    }
  }

  // core/cloud/public-api.js
  function checkedPublicGame(value) {
    if (value?.schemaVersion !== 1 || value.runtimeVersion !== "fusuma-1" || !Number.isSafeInteger(value.publicationVersion) || value.publicationVersion < 1) return failure("SERVICE_UNAVAILABLE");
    const validated = validateCloudProject(value.project, { mode: "publish" });
    return validated.ok ? ok({
      schemaVersion: 1,
      project: validated.data,
      runtimeVersion: "fusuma-1",
      publicationVersion: value.publicationVersion
    }) : failure("SERVICE_UNAVAILABLE");
  }

  // supabase/functions/shared-game/handler.js
  function createSharedGameHandler({ lookup, consumeLimit, getClientAddress, hashAddress, now = () => /* @__PURE__ */ new Date(), allowedOrigins: allowedOrigins2 }) {
    return async (request) => {
      const origin = request.headers.get("Origin");
      const headers = { "Cache-Control": "no-store", "Content-Type": "application/json; charset=utf-8", "Vary": "Origin", "X-Content-Type-Options": "nosniff" };
      if (allowedOrigins2.includes(origin)) headers["Access-Control-Allow-Origin"] = origin;
      const respond = (status, body, extra = {}) => new Response(body === null ? null : JSON.stringify(body), { status, headers: { ...headers, ...extra } });
      if (origin && !allowedOrigins2.includes(origin)) return respond(403, failure("FORBIDDEN"));
      if (request.method === "OPTIONS") return respond(204, null, { "Access-Control-Allow-Methods": "GET, OPTIONS", "Access-Control-Allow-Headers": "Content-Type" });
      if (request.method !== "GET") return respond(405, failure("UNAVAILABLE"), { "Allow": "GET, OPTIONS" });
      try {
        const address = await getClientAddress(request);
        if (!address) return respond(503, failure("SERVICE_UNAVAILABLE"));
        const hash = await hashAddress(address, now().toISOString().slice(0, 10));
        if (typeof hash !== "string" || !hash) return respond(503, failure("SERVICE_UNAVAILABLE"));
        const limit = await consumeLimit(hash);
        if (limit?.allowed === false) {
          const seconds = Math.max(1, Math.min(60, Number(limit.retry_after_seconds) || 60));
          return respond(429, failure("RATE_LIMIT", void 0, seconds), { "Retry-After": String(seconds) });
        }
        if (limit?.allowed !== true) return respond(503, failure("SERVICE_UNAVAILABLE"));
        const shareId = parseShareId(request.url);
        if (!shareId) return respond(404, failure("UNAVAILABLE"));
        const value = await lookup(shareId);
        if (!value) return respond(404, failure("UNAVAILABLE"));
        const validated = checkedPublicGame(value);
        return validated.ok ? respond(200, validated.data) : respond(503, failure("SERVICE_UNAVAILABLE"));
      } catch {
        return respond(503, failure("SERVICE_UNAVAILABLE"));
      }
    };
  }

  // supabase/functions/shared-game/client-address.js
  function canonicalAddress(value) {
    if (typeof value !== "string" || !value) return null;
    if (/^(?:0|[1-9][0-9]{0,2})(?:\.(?:0|[1-9][0-9]{0,2})){3}$/.test(value)) {
      return value.split(".").every((part) => Number(part) <= 255) ? value : null;
    }
    if (!value.includes(":") || !/^[a-fA-F0-9:.]+$/.test(value)) return null;
    if (value.includes(".") && !canonicalAddress(value.slice(value.lastIndexOf(":") + 1))) return null;
    try {
      const address = new URL(`http://[${value}]/`).hostname.slice(1, -1).toLowerCase();
      const mapped = address.match(/^::ffff:([a-f0-9]{1,4}):([a-f0-9]{1,4})$/);
      if (mapped) {
        const high = parseInt(mapped[1], 16), low = parseInt(mapped[2], 16);
        return `${high >>> 8}.${high & 255}.${low >>> 8}.${low & 255}`;
      }
      return address;
    } catch {
      return null;
    }
  }
  function readVerifiedAddress(request, mode) {
    return mode === "cloudflare-verified" ? canonicalAddress(request.headers.get("CF-Connecting-IP")) : null;
  }
  function createDailyAddressHasher(secret) {
    const encoder = new TextEncoder();
    if (typeof secret !== "string" || encoder.encode(secret).length < 32) throw new Error("Invalid hash configuration");
    const key = crypto.subtle.importKey("raw", encoder.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
    return async (value, date) => {
      const address = canonicalAddress(value);
      if (!address || !/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(Date.parse(date)) || new Date(date).toISOString().slice(0, 10) !== date) {
        throw new Error("Invalid hash input");
      }
      const message = encoder.encode(`dekiru/shared-read/v1
${date}
${address}`);
      const bytes = new Uint8Array(await crypto.subtle.sign("HMAC", await key, message));
      return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
    };
  }

  // supabase/functions/shared-game/server.js
  var allowedOrigins = ["https://ruriru-app.github.io"];
  function readServerEnvironment(getEnv) {
    try {
      const serviceUrl = getEnv("SUPABASE_URL");
      if (typeof serviceUrl !== "string" || !/^https:\/\/[a-z0-9]{20}\.supabase\.co\/?$/.test(serviceUrl)) return null;
      const modern = getEnv("SUPABASE_SECRET_KEYS");
      let serverKey, legacy = false;
      if (modern !== void 0 && modern !== null) {
        const values = JSON.parse(modern);
        serverKey = values?.default;
        if (typeof serverKey !== "string" || !/^sb_secret_[A-Za-z0-9_-]{16,}$/.test(serverKey)) return null;
      } else {
        serverKey = getEnv("SUPABASE_SERVICE_ROLE_KEY");
        if (typeof serverKey !== "string" || !/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(serverKey)) return null;
        const payload = serverKey.split(".")[1].replaceAll("-", "+").replaceAll("_", "/");
        if (JSON.parse(atob(payload)).role !== "service_role") return null;
        legacy = true;
      }
      const hashSecret = getEnv("DEKIRU_RATE_HMAC_KEY");
      if (typeof hashSecret !== "string" || new TextEncoder().encode(hashSecret).length < 32) return null;
      const clientIpMode = getEnv("DEKIRU_CLIENT_IP_MODE");
      if (clientIpMode !== "cloudflare-verified") return null;
      return { serviceUrl: serviceUrl.replace(/\/$/, ""), serverKey, legacy, hashSecret, clientIpMode };
    } catch {
      return null;
    }
  }
  function createSharedGameServer({ environment, fetchImpl = fetch, now = () => /* @__PURE__ */ new Date(), rpcTimeoutMs = 5e3 }) {
    const getEnv = typeof environment === "function" ? environment : (name) => environment?.[name];
    const settings = readServerEnvironment(getEnv);
    const hashAddress = settings ? createDailyAddressHasher(settings.hashSecret) : async () => null;
    const timeoutMs = Number.isFinite(rpcTimeoutMs) && rpcTimeoutMs > 0 ? Math.min(rpcTimeoutMs, 5e3) : 5e3;
    const rpc = async (name, args) => {
      if (!settings || !["consume_shared_read", "read_shared_game"].includes(name)) throw new Error("Unavailable");
      const controller = new AbortController();
      let timer;
      const headers = { "Content-Type": "application/json", apikey: settings.serverKey };
      if (settings.legacy) headers.Authorization = `Bearer ${settings.serverKey}`;
      try {
        const timeout = new Promise((_, reject) => {
          timer = setTimeout(() => {
            controller.abort();
            reject(new Error("Unavailable"));
          }, timeoutMs);
        });
        const operation = (async () => {
          const response = await fetchImpl(`${settings.serviceUrl}/rest/v1/rpc/${name}`, {
            method: "POST",
            headers,
            body: JSON.stringify(args),
            redirect: "error",
            cache: "no-store",
            credentials: "omit",
            signal: controller.signal
          });
          if (!response.ok) {
            controller.abort();
            throw new Error("Unavailable");
          }
          return await response.json();
        })();
        return await Promise.race([operation, timeout]);
      } finally {
        clearTimeout(timer);
      }
    };
    return createSharedGameHandler({
      allowedOrigins,
      now,
      hashAddress,
      getClientAddress: (request) => settings ? readVerifiedAddress(request, settings.clientIpMode) : null,
      consumeLimit: (hash) => rpc("consume_shared_read", { p_client_hash: hash }),
      lookup: (shareId) => rpc("read_shared_game", { p_share_id: shareId })
    });
  }

  // supabase/functions/shared-game/entry.ts
  Deno.serve(createSharedGameServer({ environment: (name) => Deno.env.get(name) }));
})();
